
--============================================================================
DECLARE
    V_ANNO DATE;
    
    
    CURSOR EMPLEADO_CURSOR
    IS 
        SELECT NUMRUT_EMP, NOMBRE_EMP, SUELDO_BASE_EMP, trunc(months_between(V_ANNO,FECING_EMP)/12) AS ANOS_EMPRESA
        FROM EMPLEADO
        ORDER BY ANOS_EMPRESA DESC;
        
   V_ASIGNACION NUMBER(30, 4);
   V_ANOS_EMPLEADO NUMBER(30);
   V_CARGA_ASIG NUMBER(30);
   V_MOVIL_ASIG NUMBER(30);
   V_COLACION NUMBER(30);
   V_COMI_VENTAS NUMBER(30);
   V_ESCOL_ASIG NUMBER(30);
   V_TOTAL NUMBER(30);
   
    
BEGIN
    V_ANNO := TO_DATE('1-2-2018');
    V_COLACION := 40000;
    V_COMI_VENTAS := 0;
    for empl in empleado_cursor
    LOOP
        V_ANOS_EMPLEADO := empl.anos_empresa;
        --buscar asignación por año
        IF v_anos_empleado <= 9 then V_ASIGNACION:= ROUND(EMPL.SUELDO_BASE_EMP * 4 /100 );
        ELSIF v_anos_empleado <= 12 then V_ASIGNACION:= ROUND(EMPL.SUELDO_BASE_EMP * 6 /100 ) ;
        ELSIF v_anos_empleado <= 16 then V_ASIGNACION:= ROUND(EMPL.SUELDO_BASE_EMP * 7 /100  );
        ELSIF v_anos_empleado <= 30 then V_ASIGNACION:= ROUND(EMPL.SUELDO_BASE_EMP * 10 /100 )  ;
        else V_ASIGNACION:= 10;
        end if;
        --fin asignacion por año guardada en V_ASIGNACION
        DECLARE
        --COMIENZO ASIGNACION POR CARGA
            V_CARGAS NUMBER;
        BEGIN
            SELECT COUNT(*) INTO V_CARGAS FROM CARGA_FAMILIAR WHERE NUMRUT_EMP = EMPL.NUMRUT_EMP;
            IF V_CARGAS != 0 THEN
                V_CARGA_ASIG := V_CARGAS * 4500;
            ELSE 
               V_CARGA_ASIG := 0;
            END IF;
        END;
        --FIN ASIGNACION POR CARGA
        --INICIO ASIGNACION POR MOVILIZACION
        IF EMPL.SUELDO_BASE_EMP <= 300000 THEN V_MOVIL_ASIG:= ROUND(EMPL.SUELDO_BASE_EMP * 50 /100 );
        ELSIF EMPL.SUELDO_BASE_EMP <= 1000000 THEN V_MOVIL_ASIG:= ROUND(EMPL.SUELDO_BASE_EMP * 50 /100 );
        ELSIF EMPL.SUELDO_BASE_EMP <= 2500000 THEN V_MOVIL_ASIG:= ROUND(EMPL.SUELDO_BASE_EMP * 20 /100 );
        ELSIF EMPL.SUELDO_BASE_EMP <= 8000000 THEN V_MOVIL_ASIG:= ROUND(EMPL.SUELDO_BASE_EMP * 5 /100 );
        ELSE V_MOVIL_ASIG := 0;
        END IF;
        --FIN ASIGNACION POR MOVILIZACION
        --COMIENZO ASIGNACION POR COMISION
        DECLARE
            V_COMI NUMBER;
        BEGIN
            SELECT SUM(C.VALOR_COMISION)
            INTO V_COMI
            FROM BOLETA  B
            LEFT JOIN COMISION_VENTA C
            ON b.nro_boleta = C.NRO_BOLETA
            WHERE B.NUMRUT_EMP = EMPL.NUMRUT_EMP;
              IF V_COMI != 0 THEN
                V_COMI_VENTAS := V_COMI;
            ELSE 
               V_COMI_VENTAS := 0;
            END IF;
        END;
        --COMIENZO AIGNACION POR ESCOLARIDAD
        DECLARE
            V_PORC NUMBER(30);
        BEGIN
            SELECT  a.porc_asig_escolaridad
            INTO V_PORC
            FROM EMPLEADO E
            LEFT JOIN ASIG_ESCOLARIDAD A
            ON e.id_escolaridad = a.id_escolaridad
            WHERE e.numrut_emp = EMPL.NUMRUT_EMP;
            V_ESCOL_ASIG := ROUND(EMPL.SUELDO_BASE_EMP * V_PORC / 100 );
        END;
        
    V_TOTAL := V_ASIGNACION +  V_ANOS_EMPLEADO + V_CARGA_ASIG + V_MOVIL_ASIG + V_COLACION + V_COMI_VENTAS + V_ESCOL_ASIG;
     --TESTS
--    DBMS_OUTPUT.PUT_LINE('NOMBRE: '||empl.NOMBRE_EMP);    
--    DBMS_OUTPUT.PUT_LINE('MOVILIZACION: '||V_MOVIL_ASIG);
--    DBMS_OUTPUT.PUT_LINE('ASIGNACION '||V_ASIGNACION);
--    DBMS_OUTPUT.PUT_LINE('CARGA:  ' ||V_CARGA_ASIG);
--    DBMS_OUTPUT.PUT_LINE('COLACION: '||V_COLACION);
--    DBMS_OUTPUT.PUT_LINE('VENTAS: '||V_COMI_VENTAS);
--    DBMS_OUTPUT.PUT_LINE('ESCOLARIDAD '||V_ESCOL_ASIG);
--    DBMS_OUTPUT.PUT_LINE('TOTAL: '||V_TOTAL);
--    DBMS_OUTPUT.PUT_LINE('AÑO: '||EXTRACT(YEAR FROM V_ANNO));
--    DBMS_OUTPUT.PUT_LINE('MES: '||EXTRACT(MONTH FROM V_ANNO));
    --INSERT INTO TALBA HABER_CAL_MES
    INSERT INTO HABER_CALC_MES(NUMRUT_EMP, MES_PROCESO, ANNO_PROCESO,
    VALOR_SUELDO_BASE, VALOR_ASIG_ANNOS, VALOR_CARGAS_FAM, 
    VALOR_MOVILIZACION, VALOR_COLACION, VALOR_COM_VENTAS, 
    VALOR_TOT_HABERES)
    VALUES(EMPL.NUMRUT_EMP, EXTRACT(MONTH FROM V_ANNO), EXTRACT(YEAR FROM V_ANNO),
    EMPL.SUELDO_BASE_EMP, V_ASIGNACION,V_CARGA_ASIG,
    V_MOVIL_ASIG,V_COLACION, V_COMI_VENTAS,
    V_TOTAL);
    END LOOP;
    
END;