<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-15 19:28
=======
# Generated by Django 3.2.4 on 2021-06-15 17:39
>>>>>>> 8b0a8253f92bc67ce0e03925e53cc3f97181f163

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(max_length=9)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CP', 'Corporativo'), ('BN', 'Bancario'), ('DF', 'Defensa'), ('AD', 'Administrativo'), ('IM', 'Inmobiliario'), ('SG', 'Seguros'), ('MA', 'Medioambiente')], default='DF', max_length=2)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
