# Generated by Django 3.2.4 on 2021-06-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210615_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='rut',
            new_name='cliente',
        ),
    ]
