# Generated by Django 3.2.4 on 2021-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
