# Generated by Django 3.2.3 on 2021-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('RV', 'Revisión'), ('AP', 'Aprobado'), ('RC', 'Rechazado')], default='RV', max_length=2),
        ),
    ]
