# Generated by Django 3.2.3 on 2021-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(default='lorem'),
        ),
    ]
