# Generated by Django 3.2.3 on 2021-06-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitud_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(default='0', null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='core.solicitud')),
            ],
        ),
    ]
