# Generated by Django 3.2.3 on 2021-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_presupuestocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocliente',
            name='valor',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
