# Generated by Django 3.2.3 on 2021-06-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_presupuestocliente_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contrato', models.FileField(upload_to='')),
                ('estado', models.CharField(choices=[('RV', 'Revisión'), ('FM', 'Firmado'), ('RC', 'Rechazado')], default='RV', max_length=2)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='core.solicitud')),
            ],
        ),
    ]
