# Generated by Django 3.2.3 on 2021-06-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notificacioncliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocliente',
            options={'verbose_name': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='notificacioncliente',
            options={'verbose_name': 'Notificacione'},
        ),
        migrations.AlterModelOptions(
            name='presupuestocliente',
            options={'verbose_name': 'Presupuesto'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitude'},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Causas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('tribunal', models.CharField(max_length=200)),
                ('etapa', models.CharField(choices=[('IN', 'Inicio'), ('PR', 'Preparación'), ('JC', 'Juicio'), ('AP', 'Apelación'), ('PB', 'Prueba'), ('CT', 'Citación'), ('EH', 'Exhorto'), ('IP', 'Impune')], default='IN', max_length=2)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='core.contratocliente')),
            ],
        ),
    ]
