# Generated by Django 3.2.3 on 2021-06-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210627_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Causas',
            new_name='Causa',
        ),
    ]
