# Generated by Django 3.2.4 on 2021-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_causas_causa'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocliente',
            name='pagado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='tribunal',
            field=models.CharField(default='1º Juzgado Civil de Santiago', max_length=200),
        ),
    ]
