# Generated by Django 3.2.4 on 2021-07-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210629_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=60)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('exp', models.DateField()),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_pagar', to='core.presupuestocliente')),
            ],
        ),
    ]
