# Generated by Django 3.2.4 on 2021-07-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pagocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocliente',
            name='valor',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
